trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Models/QuestionPool/CreateQuestionView.cs
/****************************************************************************************
 * Copyright © attune Lanka (Private) Limited. All rights reserved.                     *
 * No part of this publication may be reproduced, transmitted, transcribed,             *
 * stored in a retrieval system, or translated into any language,                       *
 * in any form or by any means, electronic, mechanical, photocopying,                   *
 * recording, or otherwise, without prior written permission from attune.               *
 *                                                                                      *
 * All copyright, confidential information, patents, design rights and                  *
 * all other intellectual property rights of whatsoever nature in and                   *
 * to any source code contained herein (including any header files and                  *
 * demonstration code that may be included), are and shall remain the sole and          *
 * exclusive property of attune.                                                        *
 *                                                                                      *
 * The information furnished herein is believed to be accurate and reliable.            *
 * However, no responsibility is assumed by attune for its use, or for any              *
 * infringements of patents or other rights of third parties resulting from its use.    *
 *                                                                                      *
 ***************************************************************************************/

using System.ComponentModel.DataAnnotations;
using attune.Core.Web.Mvc.Attributes;
using attune.Exam.Infrastructure.Resources;

namespace attune.Exam.Web.Areas.Master.Models.QuestionPool
{
    public class CreateQuestionView : Application.Dtos.QuestionPool
    {
        public CreateQuestionView()
        {
            this.IsActive = true;
        }

        [Display(Name = "MasterQuestionBankLabelExamType", ResourceType = typeof(Labels))]
        [UIHint("OnChangeExamType")]
        [Required]
        public int ExamTypeId { get; set; }

        [Display(Name = "MasterQuestionBankLabelCategory", ResourceType = typeof(Labels))]
        [Required]
        [UIHint("CascadeCategory")]
        public int CategoryId { get; set; }

        [Display(Name = "MasterQuestionBankLabelDifficultLevel", ResourceType = typeof(Labels))]
        [Required]
        [UIHint("DifficultLevel")]
        public int DifficultLevelId { get; set; }

        [Display(Name = "MasterQuestionBankLabelQuestionType", ResourceType = typeof(Labels))]
        [Required]
        [UIHint("QuestionType")]
        public int QuestionTypeId { get; set; }

        [Display(Name = "MasterQuestionBankLabelQuestion", ResourceType = typeof(Labels))]
        [Required]
        public override string Question
        {
            get { return base.Question; }
            set { base.Question = value; }
        }

        public string AnswersString { get; set; }
        public string PublishedMode { get; set; }
        public string ddlExamType { get; set; }
        public string ddlCategory { get; set; }
        
    }
}

trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Models/QuestionPool/FilterView.cs
/****************************************************************************************
 * Copyright © attune Lanka (Private) Limited. All rights reserved.                     *
 * No part of this publication may be reproduced, transmitted, transcribed,             *
 * stored in a retrieval system, or translated into any language,                       *
 * in any form or by any means, electronic, mechanical, photocopying,                   *
 * recording, or otherwise, without prior written permission from attune.               *
 *                                                                                      *
 * All copyright, confidential information, patents, design rights and                  *
 * all other intellectual property rights of whatsoever nature in and                   *
 * to any source code contained herein (including any header files and                  *
 * demonstration code that may be included), are and shall remain the sole and          *
 * exclusive property of attune.                                                        *
 *                                                                                      *
 * The information furnished herein is believed to be accurate and reliable.            *
 * However, no responsibility is assumed by attune for its use, or for any              *
 * infringements of patents or other rights of third parties resulting from its use.    *
 *                                                                                      *
 ***************************************************************************************/

using System.ComponentModel.DataAnnotations;
using attune.Core.Web.Mvc.Attributes;
using attune.Exam.Infrastructure.Resources;

namespace attune.Exam.Web.Areas.Master.Models.QuestionPool
{
    public class FilterView
    {
        [Display(Name = "MasterQuestionBankLabelExamType", ResourceType = typeof(Labels))]
        [UIHint("ExamType")]
        [Required]
        public int ExamTypeId { get; set; }

        [Display(Name = "MasterQuestionBankLabelCategory", ResourceType = typeof(Labels))]
        [UIHint("Category")]
        public int? CategoryId { get; set; }

        [Display(Name = "MasterQuestionBankLabelDifficultLevel", ResourceType = typeof(Labels))]
        [UIHint("DifficultLevel")]
        public int? DifficultLevelId { get; set; }

        [Display(Name = "MasterQuestionBankLabelQuestionMode", ResourceType = typeof(Labels))]
        [UIHint("QuestionMode")]
        public bool? IsPublished { get; set; }
    }
}

trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Controllers/QuestionBankController.cs
/****************************************************************************************
 * Copyright © attune Lanka (Private) Limited. All rights reserved.                     *
 * No part of this publication may be reproduced, transmitted, transcribed,             *
 * stored in a retrieval system, or translated into any language,                       *
 * in any form or by any means, electronic, mechanical, photocopying,                   *
 * recording, or otherwise, without prior written permission from attune.               *
 *                                                                                      *
 * All copyright, confidential information, patents, design rights and                  *
 * all other intellectual property rights of whatsoever nature in and                   *
 * to any source code contained herein (including any header files and                  *
 * demonstration code that may be included), are and shall remain the sole and          *
 * exclusive property of attune.                                                        *
 *                                                                                      *
 * The information furnished herein is believed to be accurate and reliable.            *
 * However, no responsibility is assumed by attune for its use, or for any              *
 * infringements of patents or other rights of third parties resulting from its use.    *
 *                                                                                      *
 ***************************************************************************************/

using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using attune.Core.Adaptor;
using attune.Core.Helpers;
using attune.Core.Web.Mvc.Attributes;
using attune.Core.Web.Mvc.Controllers;
using attune.Exam.Application.Interfaces;
using attune.Exam.Domain.Queries;
using attune.Exam.Infrastructure.Resources;
using attune.Exam.Web.Areas.Master.Models;
using attune.Exam.Web.Helpers;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using OfficeOpenXml;
using Constants = attune.Exam.Web.Helpers.Constants;
using attune.Exam.Application.Dtos;
using attune.Exam.Domain;
using attune.Exam.Web.Areas.Master.Models.QuestionBank;
using attune.Exam.Web.Extentions;
using AutoMapper.Internal;

namespace attune.Exam.Web.Areas.Master.Controllers
{
    public partial class QuestionBankController : UnauthorizedControllerBase
    {
        #region Private Variables

        private readonly IQuestionBankService _questionBankService;
        private readonly IMasterDataService _masterDataService;
        private readonly IAdaptor _adaptor;
        #endregion

        #region Public Methods

        /// <summary>
        /// Initializes a new instance of the <see cref="QuestionBankController"/> class.
        /// </summary>
        /// <param name="questionBankService">The question Bank service.</param>
        /// <param name="masterDataService"></param>
        public QuestionBankController(IQuestionBankService questionBankService, IMasterDataService masterDataService, IAdaptor adaptor)
        {
            _questionBankService = questionBankService;
            _masterDataService = masterDataService;
            _adaptor = adaptor;

            Populate();
        }

        // GET: QuestionBank/QuestionBank
        public ActionResult Index(string param)
        {
            return View(new QuestionBankView());
        }

        #region Qustion bank grid events

        /// <summary>
        /// QuestionBank Grid Read
        /// </summary>
        /// <param name="request"></param>
        /// <param name="query"></param>
        /// <returns></returns>
        [CompressFilter]
        public ActionResult OnQuestionBankGridRead([DataSourceRequest] DataSourceRequest request, QuestionQuery query)
        {
            if (query!=null && query.ExamTypeId!=0)
            {
                return Json(_questionBankService.FindQuestions(query).ToDataSourceResult(request),
               JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new JsonResult(),
               JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Question Deactivate
        /// </summary>
        /// <param name="request"></param>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult OnQuestionDeactivate([DataSourceRequest] DataSourceRequest request, string Id)
        {
            object result = null;
            try
            {
                var question = _questionBankService.FindQuestion(Convert.ToInt64(Id));
                question.IsActive = false;
                question.UpdatedOn = DateTime.Now;
                question.UpdatedBy = 1;//TODO:LoggedIn user Id
                if (_questionBankService.DeActivateQuestion(question))
                    result =
                        new {Message = Messages.MasterQuestionBankDeActivateSuccess, Type = MessageType.Success};
                else
                    result =
                        new {Message = Messages.CommonRecordSaveFailed, Type = MessageType.Error};
            }
            catch (Exception ex)
            {
                result=new { Message = Messages.CommonRecordSaveFailed, Type = MessageType.Error };
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Question Publish
        /// </summary>
        /// <param name="request"></param>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult OnQuestionPublish([DataSourceRequest] DataSourceRequest request, string Id)
        {
            object result = null;
            try
            {
                var question = _questionBankService.FindQuestion(Convert.ToInt64(Id));
                question.IsPublished = true;
                question.UpdatedOn = DateTime.Now;
                question.UpdatedBy = 1;//TODO:LoggedIn user Id
                    if (_questionBankService.UpdateQuestion(question))
                    result =
                        new {Message = Messages.MasterQuestionBankPublishSuccess, Type = MessageType.Success};
                else
                    result =
                        new {Message = Messages.CommonRecordSaveFailed, Type = MessageType.Error};
            }
            catch (Exception ex)
            {
                result=new { Message = ex.Message, Type = MessageType.Error };
                
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Question DownLoad Template
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult OnQuestionDownLoadTemplate([DataSourceRequest] DataSourceRequest request)
        {
            var serverPath = System.Web.HttpContext.Current.Server.MapPath(Constants.EXCEL_PATH);
            const string fileName = Constants.EXCEL_NAME;
            var filepath = Path.Combine(serverPath, fileName);

            Response.AddHeader("content-disposition", filepath);
            Response.ContentType = "application/vnd.ms-excel";
            Response.BufferOutput = true;
            Response.ContentEncoding = Encoding.UTF8;
            Response.Charset = "UTF-8";

            return Json(filepath, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Download Excel
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpGet]
        public virtual ActionResult Download(string file)
        {
            if (file != null)
            {
                var fileName = file.Substring(file.LastIndexOf("\\", StringComparison.Ordinal) + 1).Trim();
                var fullPath = Path.Combine(Server.MapPath(Constants.EXCEL_TEMP_PATH), file);
                return File(fullPath, "application/vnd.ms-excel", fileName);
            }
            return null;
        }

        /// <summary>
        /// Question Upload
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public ActionResult OnQuestionUpload(HttpPostedFileBase file)
        {
            ExcelWorksheet worksheet;
            var uploadResult = UploadHelper.ParsePostedFile(file, out worksheet);
            var result = new object { };
            if (uploadResult.ErrorType == UploadErrorType.None && worksheet != null)
            {
                DataTable dt = UploadHelper.ToDataTable(worksheet);
                dt.ConvertToBool(4);
                var list = dt.ToList<Application.Dtos.UploadQuestion>();
                if (list.Count > 0)
                {
                    var val = _questionBankService.AddBulkQuestions(list);
                    if (val)
                        return Json(new
                                    {
                                        UploadResult = uploadResult,
                                        Message = Messages.MasterQuestionBankUploadSuccess,
                                        Type = MessageType.Success
                                    }, JsonRequestBehavior.AllowGet);
                    else
                        return Json(new
                                    {
                                        UploadResult = uploadResult,
                                        Message = Messages.MasterQuestionBankUploadErrorOccured,

trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Views/QuestionPool/Create.cshtml

@{
    ViewBag.Title = "Create";
}

<h2>CreateQuestion</h2>


trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Views/QuestionPool/Index.cshtml
@model attune.Exam.Web.Areas.Master.Models.QuestionPool.QuestionPoolView
@{
    ViewBag.Title = "LayoutNavigationQuestionPool";
}

@using (Html.BeginForm())
{
    <div class="employ-filters up-lvl show" id="sticky">
        <p>Filter: <i class="att att-caret-down"></i></p>
        <div class="box">
            <div class="col-sm-3 req">
                @Html.EditorFor(x => x.FilterView.ExamTypeId)
            </div>
            <div class="col-sm-3">
                @Html.EditorFor(x => x.FilterView.CategoryId)
            </div>
            <div class="col-sm-3">
                @Html.EditorFor(x => x.FilterView.DifficultLevelId)
            </div>
            <div class="col-sm-3 mode_wrap">
                @Html.EditorFor(x => x.FilterView.IsPublished)
                <button type="button" class="default_btn green_btn att att-search" id="btnGo"></button>
            </div>
        </div>
    </div>

}

<div class="middle_section">
    <div id="divQsBank" class="ab_grid">
        @(Html.Kendo().Grid(Model.GridView.DataSource)
          .Name("grdQuestionPool")
          .Columns(columns =>
                   {
                       columns.Bound(p => p.Id).ClientTemplate("<a class='blue_icon hover_disable_blue att' href='" + Url.Action("Edit", "QuestionBank", new { Id = "#=Id#" }) + "' data-mode='edit' ><i class='att att-edit (alias)'></i></a>").Title("").Width(40).Sortable(false);
                       columns.Bound(p => p.Id).ClientTemplate("<button class='no_bg red_icon' data-mode='deactivate' rowId='#=Id#'><i class='att att-times-circle'></i></button>").Title("").Width(50).Sortable(false);
                       columns.Bound(p => p.Id).ClientTemplate("<button class='no_bg green_icon' data-mode='publish' rowId='#=Id#'><i class='att att-arrow-circle-up'></i></button>").Title("").Width(50).Sortable(false);
                       columns.Bound(p => p.Id).Hidden(true);
                       columns.Bound(p => p.ExamType.Name).Sortable(true).Title(@L("MasterQuestionBankGridHeaderExamType").ToString()).Width(130);
                       columns.Bound(p => p.Category.Name).Sortable(true).Title(@L("MasterQuestionBankGridHeaderCategory").ToString()).Width(130);
                       columns.Bound(p => p.DifficultLevel).Sortable(false).Title(@L("MasterQuestionBankGridHeaderDifficultLevel").ToString()).Width(130);
                       columns.Bound(p => p.Question).Sortable(false).Title(@L("MasterQuestionBankGridHeaderQuestion").ToString());
                       columns.Bound(p => p.IsPublished).Hidden();
                   })

          .Events(x =>
                  {
                      x.DataBound("Exam.Handlers.QuestionBank.onDataBound");
                  })
          .Pageable(pager => pager
              .Input(Model.GridView.PagerView.Input)
              .Numeric(Model.GridView.PagerView.Numeric)
              .Info(Model.GridView.PagerView.Info)
              .PreviousNext(Model.GridView.PagerView.PreviousNext)
              .Refresh(Model.GridView.PagerView.Refresh)
              .PageSizes(Model.GridView.PagerView.PageSizes)
          )
          .ToolBar(toolBar =>
                   {
                       toolBar.Template(@<text>
                        <a href="@Url.Action("Create", "QuestionBank")" class="default_btn green_btn k-button k-button-icontext att att-plus"><span class="btn_text">@L("MasterQuestionBankButtonAdd").ToString()</span></a>
                        <a href="#" class="default_btn blue_btn k-button k-button-icontext att att-upload" id="uploadQuestionWindow"><span class="btn_text">@L("MasterQuestionBankButtonUpload").ToString()</span></a>
                        <a href="#" class="default_btn green_btn k-button k-button-icontext att att-download" id="downLoadTemplate"><span class="btn_text">@L("MasterQuestionBankButtonDownLoadTemplate").ToString()</span></a>
                    </text>);
                   })
                                                                          .Sortable(x => x.Enabled(true))
                                                                          .AutoBind(false)
                                                                          .Scrollable(x => x.Height("auto"))
                                                                          .Selectable(selectable => selectable.Mode(GridSelectionMode.Single))
                                                                          .DataSource(dataSource => dataSource
                                                                              .Ajax()
                                                                              .ServerOperation(false)
                                                                              .Model(model =>
                                                                                     {
                                                                                         model.Id(p => p.Id);
                                                                                     })
                                                                              .PageSize(10)
                                                                              //.Read(read => read.Action("OnQuestionBankGridRead", "QuestionBank").Data("Exam.Handlers.QuestionBank.getGridParameters"))

                                                                          )
        )
    </div>
</div>

<div id="uploadPopup">
    @(Html.Kendo().Window()
        .Name("uploadWindow")
                        .Title(@L("MasterQuestionBankPopupUploadTitle").ToString())
        .Modal(true)
        .Draggable()
        .Visible(false)
        .Content(@<text>
            <div id="upload">

                <div class="k-content">
                    <div>
                        <input name="file" id="file" type="file" class="ffff" />
                    </div>
                    <div id="upload-errors" class="popup_error_msg" style="display: none;"></div>
                </div>
            </div>

        </text>)
                                          .Actions(x =>
                                          {
                                              x.Close();
                                          }).Events(x => x.Open("Exam.Handlers.QuestionPool.onOpenUploadPopUp"))

                                           .Width(500)
    )
</div>