trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Models/Exam/CreateExamView.cs
/****************************************************************************************
 * Copyright © attune Lanka (Private) Limited. All rights reserved.                     *
 * No part of this publication may be reproduced, transmitted, transcribed,             *
 * stored in a retrieval system, or translated into any language,                       *
 * in any form or by any means, electronic, mechanical, photocopying,                   *
 * recording, or otherwise, without prior written permission from attune.               *
 *                                                                                      *
 * All copyright, confidential information, patents, design rights and                  *
 * all other intellectual property rights of whatsoever nature in and                   *
 * to any source code contained herein (including any header files and                  *
 * demonstration code that may be included), are and shall remain the sole and          *
 * exclusive property of attune.                                                        *
 *                                                                                      *
 * The information furnished herein is believed to be accurate and reliable.            *
 * However, no responsibility is assumed by attune for its use, or for any              *
 * infringements of patents or other rights of third parties resulting from its use.    *
 *                                                                                      *
 ***************************************************************************************/

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;
using attune.Core.Web.Mvc.Attributes;
using attune.Exam.Domain.Entities;
using attune.Exam.Infrastructure.Resources;
using QuestionCategory = attune.Exam.Application.Dtos.QuestionCategory;

namespace attune.Exam.Web.Areas.Master.Models.Exam
{
    public class CreateExamView : Application.Dtos.Exam
    {
        public CreateExamView()
        {
            this.IsActive = true;
            
        }
        public int mode { get; set; }
        public int ExamId { get; set; }

        [Display(Name = "MasterExamLabelExamType", ResourceType = typeof (Labels))]
        [UIHint("ExamOnChangeExamType")]
        [Required]
        public int ExamTypeId { get; set; }
        
        [Display(Name = "MasterExamLabelDifficultLevel", ResourceType = typeof (Labels))]
        [Required]
        [UIHint("DifficultLevel")]
        public int DifficultLevel { get; set; }

        [Required]
        [Display(Name = "MasterExamLabelExamName", ResourceType = typeof (Labels))]
        public override string Name { get; set; }

        [Display(Name = "MasterExamLabelExamDescription", ResourceType = typeof (Labels))]
        public override string Description { get; set; }

        [Required]
        [Display(Name = "MasterExamLabelDuration", ResourceType = typeof(Labels))]
        [RegularExpression(@"[-+]?[0-9]*\.?[0-9]?[0-9]", ErrorMessageResourceName = "MasterExamIntegerValidationDuration", ErrorMessageResourceType = typeof(Messages))] 
        [Range(1, 99, ErrorMessageResourceName = "MasterExamIntegerValidationDuration", ErrorMessageResourceType = typeof(Messages))]
        public new decimal? Duration { get; set; }

        [Required]
        [UIHint("QuestionPick")]
        [Display(Name = "MasterExamLabelQuestionPickining", ResourceType = typeof (Labels))]
        public new bool? IsManualPick { get; set; }

        [Required]
        [UIHint("ResultFormatType")]
        [Display(Name = "MasterExamLabelShowResults", ResourceType = typeof (Labels))]
        public int ResultFormatTypeId { get; set; }

        [Display(Name = "MasterExamLabelPassMarks", ResourceType = typeof(Labels))]
        [RegularExpression(@"[-+]?[0-9]*\.?[0-9]?[0-9]", ErrorMessageResourceName = "MasterExamIntegerValidationPassScore", ErrorMessageResourceType = typeof(Messages))] 
        [Range(1, 100, ErrorMessageResourceName = "MasterExamIntegerValidationPassScore", ErrorMessageResourceType = typeof(Messages))]
        [Required]
        public new decimal? PassScore { get; set; }
        
        public string ddlExamType { get; set; }

        public new List<QuestionCategoryView> QuestionCategories { get; set; }

        public string QuestionCategoryString { get; set; }

    }

    public class QuestionCategoryView : Application.Dtos.QuestionCategory
    {
        [Display(Name = "MasterExamLabelDifficultLevel", ResourceType = typeof(Labels))]
        [UIHint("KDifficultLevel")]
        public KeyValuePair<string, string> DifficultLevelId { get; set; }

        [UIHint("KCategory")]
        [Display(Name = "MasterExamLabelCategory", ResourceType = typeof(Labels))]
        public KeyValuePair<string, string> CategoryId { get; set; }

        [StringLength(2, ErrorMessageResourceName = "MasterExamIntegerLengthValidationNoOfQuestion", ErrorMessageResourceType = typeof(Messages))]
        [Range(0, int.MaxValue, ErrorMessageResourceName = "MasterExamIntegerValidationNoOfQuestion", ErrorMessageResourceType = typeof(Messages))]
        [DataType(DataType.Text)]
        [Display(Name = "MasterExamNoOfQuestion", ResourceType = typeof(Labels))]
        public int? CountValue { get; set; }

        
        public List<QuestionSelectionView> QuestionSelection { get; set; }

        [ScriptIgnore]
        public new int? Count { get; set; }
    }

  }

trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Controllers/ExamController.cs
/****************************************************************************************
 * Copyright © attune Lanka (Private) Limited. All rights reserved.                     *
 * No part of this publication may be reproduced, transmitted, transcribed,             *
 * stored in a retrieval system, or translated into any language,                       *
 * in any form or by any means, electronic, mechanical, photocopying,                   *
 * recording, or otherwise, without prior written permission from attune.               *
 *                                                                                      *
 * All copyright, confidential information, patents, design rights and                  *
 * all other intellectual property rights of whatsoever nature in and                   *
 * to any source code contained herein (including any header files and                  *
 * demonstration code that may be included), are and shall remain the sole and          *
 * exclusive property of attune.                                                        *
 *                                                                                      *
 * The information furnished herein is believed to be accurate and reliable.            *
 * However, no responsibility is assumed by attune for its use, or for any              *
 * infringements of patents or other rights of third parties resulting from its use.    *
 *                                                                                      *
 ***************************************************************************************/

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using attune.Core.Adaptor;
using attune.Core.Helpers;
using attune.Core.Web.Mvc.Attributes;
using attune.Core.Web.Mvc.Controllers;
using attune.Exam.Application.Dtos;
using attune.Exam.Application.Interfaces;
using attune.Exam.Domain;
using attune.Exam.Domain.Queries;
using attune.Exam.Web.Areas.Master.Models.Exam;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using attune.Exam.Infrastructure.Resources;
using attune.Exam.Web.Extentions;
using attune.Exam.Web.Helpers;

namespace attune.Exam.Web.Areas.Master.Controllers
{
    public class ExamController : UnauthorizedControllerBase
    {
        #region Private Variables

        private readonly IQuestionPoolService _questionBankService;
        private readonly IMasterDataService _masterDataService;
        private readonly IAdaptor _adaptor;
        #endregion

        #region Public Methods

        /// <summary>
        /// Exam Controller
        /// </summary>
        /// <param name="questionBankService"></param>
        /// <param name="masterDataService"></param>
        /// <param name="adaptor"></param>
        public ExamController(IQuestionPoolService questionBankService, IMasterDataService masterDataService, IAdaptor adaptor)
        {
            _questionBankService = questionBankService;
            _masterDataService = masterDataService;
            _adaptor = adaptor;
            Populate();
        }

        // GET: Master/Exam
        public ActionResult Index()
        {
            return View(new ExamView());
        }

        #region Drop Down Load

        /// <summary>
        /// On Exam Name Read
        /// </summary>
        /// <param name="examTypeId"></param>
        /// <returns></returns>
        [CompressFilter]
        public ActionResult OnExamNameRead(int examTypeId)
        {
            return Json(_masterDataService.GetExamNames(examTypeId), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// On Category Read
        /// </summary>
        /// <param name="examTypeId"></param>
        /// <returns></returns>
        public ActionResult OnCategoryRead(int examTypeId)
        {
            return Json(_masterDataService.GetCategories(examTypeId), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// On Result Format Type Read
        /// </summary>
        /// <returns></returns>
        [CompressFilter]
        public ActionResult OnResultFormatTypeRead()
        {
            return Json(_masterDataService.GetResultFormatType(), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Exam Grid events

        /// <summary>
        /// On Exam Manager Grid Read
        /// </summary>
        /// <param name="request"></param>
        /// <param name="query"></param>
        /// <returns></returns>
        [CompressFilter]
        public ActionResult OnExamManagerGridRead([DataSourceRequest] DataSourceRequest request, ExamQuery query)
        {
            if (query != null && query.ExamTypeId != 0)
            {
                return Json(_questionBankService.FindExams(query).ToDataSourceResult(request),
               JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new JsonResult(),
               JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// On Exam De activate
        /// </summary>
        /// <param name="request"></param>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult OnExamDeactivate([DataSourceRequest] DataSourceRequest request, string Id)
        {
            object result = null;
            try
            {
                var exam = _questionBankService.FindExam(Convert.ToInt64(Id));
                exam.IsActive = false;
                exam.UpdatedOn = DateTime.Now;
                exam.UpdatedBy = 1;//TODO:LoggedIn user Id
                if (_questionBankService.DeActivateExam(exam))
                    result =
                        new { Message = Messages.MasterExamDeActivateSuccess, Type = MessageType.Success };
                else
                    result =
                        new { Message = Messages.CommonRecordSaveFailed, Type = MessageType.Error };
            }
            catch (Exception ex)
            {
                result = new { Message = Messages.CommonRecordSaveFailed, Type = MessageType.Error };
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        
        #endregion

        #region Exam Add

        /// <summary>
        /// Create
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
          return View("Create", new CreateExamView());
        }

        /// <summary>
        /// Create
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(CreateExamView model)
        {
            if (!ModelState.IsValid) return View(model);
            var response = new Response<string>();
            try
            {
                var dto = new Application.Dtos.Exam();
                dto.QuestionCategories=new List<QuestionCategory>();
                model.ExamTypeId = Convert.ToInt32(model.ddlExamType);
                model.QuestionCategories =Newtonsoft.Json.JsonConvert.DeserializeObject<List<QuestionCategoryView>>(model.QuestionCategoryString);
                AssignValues(model, dto);
                response.IsSuccess = _questionBankService.AddExam(dto);
            }
            catch (Exception ex)
            {
                response.IsSuccess = false;
                response.Message = ex.Message;
                response.MessageType = MessageType.Error;
                throw;
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Exam Edit
        /// <summary>
        /// Edit
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult Edit(string Id)
        {
            var result = _questionBankService.FindExam(Convert.ToInt64(Id));
            var examModel = new CreateExamView();
            examModel.mode = (int) ExamMode.Edit;
            examModel.ExamTypeId = (int) result.ExamType.Id;
            examModel.ddlExamType = result.ExamType.Id.ToString();
            examModel.DifficultLevel = (int)result.DifficultLevelId;
            examModel.Name = result.Name;
            examModel.Description = result.Description;
            examModel.Duration = result.Duration;
            examModel.IsManualPick = result.IsManualPick;
            examModel.ResultFormatTypeId = (int)result.ResultFormatType;
            examModel.PassScore = result.PassScore;
            examModel.Id = result.Id;
            examModel.ExamId = result.Id;
            examModel.QuestionCategories=new List<QuestionCategoryView>();
            foreach (var questionCategory in result.QuestionCategories)
            {
                var categoryView = new QuestionCategoryView()
                                   {
                                       Id = questionCategory.Id,
                                       CategoryId =
                                           new KeyValuePair<string, string>(questionCategory.Category.Id.ToString(),
                                           questionCategory.Category.Name),
                                       DifficultLevelId =
                                           new KeyValuePair<string, string>(Convert.ToInt32(questionCategory.DifficultLevel).ToString(),
                                           questionCategory.DifficultLevel.ToString()),
                                       CountValue = questionCategory.Count,
                                       Questions = questionCategory.Questions

trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Views/Exam/Create.cshtml
@using attune.Exam.Web.Areas.Master.Models.Exam
@model attune.Exam.Web.Areas.Master.Models.Exam.CreateExamView
@{
    ViewBag.Title = @L("MasterExamCreationTitle");
}

@using (Html.BeginForm())
{
    <div class="employ-filters up-lvl show" id="sticky">
        <div class="box">
            <div class="col-xs-6 req">
                @Html.LabelFor(x => x.ExamTypeId)
                @Html.EditorFor(x => x.ExamTypeId)
            </div>
            <div class="col-xs-6 req">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name, new { placeholder = @L("MasterExamLabelExamName") })
            </div>
            <div class="col-xs-6 clearfix2 req">
                @Html.LabelFor(x => x.DifficultLevel)
                @Html.EditorFor(x => x.DifficultLevel)
            </div>
            <div class="col-xs-6 req">
                @Html.LabelFor(x => x.IsManualPick)
                @Html.EditorFor(x => x.IsManualPick)
            </div>
            <div class="col-xs-6 clearfix2 req">
                @Html.LabelFor(x => x.ResultFormatTypeId)
                @Html.EditorFor(x => x.ResultFormatTypeId)
            </div>
            <div class="col-xs-6 req">
                @Html.LabelFor(x => x.Duration)
                @Html.TextBoxFor(x => x.Duration, new { placeholder = @L("MasterExamLabelDuration") })
            </div>
            <div class="col-xs-6 clearfix2 req">
                @Html.LabelFor(x => x.PassScore)
                @Html.TextBoxFor(x => x.PassScore, new { placeholder = @L("MasterExamLabelPassMarks") })
            </div>
            <div class="col-xs-6">
                @Html.LabelFor(x => x.Description)
                @Html.TextAreaFor(x => x.Description, new { rows = 2, cols = 35, placeholder = @L("MasterExamLabelExamDescription") })
            </div>
        </div>
    </div>


    <div class="middle_section">
        <div id="divQsBank" class="ab_grid">
            @(Html.Kendo().Grid(Model.QuestionCategories)
                  .Name("gridQuestionCategory")
                  .Columns(columns =>
                           {
                               columns.Bound(p => p.Id).Hidden(true);
                               columns.Bound(p => p.CategoryId).ClientTemplate("#= CategoryId.Value #").Width(150).Title(@L("MasterExamGridHeaderCategory").Text);
                               columns.Bound(p => p.DifficultLevelId).ClientTemplate("#= DifficultLevelId.Value #").Width(150).Title(@L("MasterExamGridHeaderDifficultLevel").Text);
                               columns.Bound(p => p.CountValue).Width(80);
                               columns.Bound(p => p.Id).ClientTemplate("<button class='no_bg blue_icon hover_disable_blue' id='editCategory' data-mode='edit' rowId='#=Id#'><i class='att att-edit (alias)'></i></button>").Title("").Width(20);
                               columns.Bound(p => p.Id).ClientTemplate("<button class='no_bg orange_icon' id='viewCategory' data-mode='view' rowId='#=Id#'><i class='att att-eye'></i></button>").Title("").Width(20);
                               columns.Bound(p => p.Id).ClientTemplate("<button class='no_bg red_icon' data-mode='delete' rowId='#=Id#'><i class='att att-times-circle'></i></button>").Title("").Width(20);
                               //columns.Command(command => command.Destroy()).Width(20);

                           })
                  .Editable(x =>
                            {
                                x.Mode(GridEditMode.InCell);
                            })
                  .Events(x =>
                          {
                              x.Edit("Exam.Handlers.ExamManager.onEditCategory");
                              x.DataBound("Exam.Handlers.ExamManager.onDataBoundCategory");
                          }).Scrollable(x => x.Height("100px"))
                .ToolBar(toolBar =>
                 {
                     toolBar.Template(@<text>
                        <a href="#" class="default_btn green_btn k-button k-button-icontext att att-plus" id="aRowAdd"><span class="btn_text">@L("MasterExamButtonAdd").ToString()</span></a>
                    </text>);
                 })

                                                                                                  .DataSource(dataSource => dataSource
                                                                                                      .Ajax()
                                                                                                      .Batch(true)
                                                                                                      .PageSize(10)
                                                                                                      .ServerOperation(false)
                                                                                                      .Model(model =>
                                                                                                      {
                                                                                                          model.Id(p => p.Id);
                                                                                                          model.Field(x => x.DifficultLevelId).DefaultValue(new KeyValuePair<string, string>("1", "Beginner"));
                                                                                                          model.Field(x => x.CategoryId).DefaultValue(new KeyValuePair<string, string>("", @L("MasterQuestionBankDropDownCategoryOptionLabel").Text.ToString()));
                                                                                                          model.Field(x => x.Id).Editable(false);
                                                                                                      })


                                                                                                    )
            )
        </div>
    </div>

    <div class="button_row">
        <button id="btnCreate" class="default_btn green_btn att att-plus"><span class="btn_text">@L("MasterQuestionBankButtonCreate")</span></button>
    </div>

    @Html.HiddenFor(x => x.QuestionCategoryString)
}


<div id="selection">
    @(Html.Kendo().Window()
                .Name("questionSelectionPopup")
                .Title(@L("MasterExamPopupTitleSelectQuestion").Text)
        .Modal(true)
        .Draggable()
        .Visible(false)
        .Width(700)
          .Actions(x => x.Close())
            // .Height(400)
    )
</div>


trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Views/Exam/Index.cshtml
@model attune.Exam.Web.Areas.Master.Models.Exam.ExamView
@{
    ViewBag.Title = @L("LayoutNavigationExamManager");

}

@using (Html.BeginForm())
{

    <div class="employ-filters up-lvl show" id="sticky">
        <p>Filter: <i class="att att-caret-down"></i></p>
        <div class="box">
            <div class="col-xs-6 col-sm-3 req">
                @Html.EditorFor(x => x.FilterView.ExamTypeId)
            </div>
            <div class="col-xs-6 col-sm-3 mode_wrap">
                @Html.EditorFor(x => x.FilterView.ExamId)
                <button type="button" class="default_btn green_btn att att-search" id="btnGo"></button>
            </div>
            
        </div>
    </div>

}

<div class="middle_section">
    <div id="divQsBank" class="ab_grid">
        @(Html.Kendo().Grid(Model.GridView.DataSource)
          .Name("grdExamManager")
          .Columns(columns =>
                   {
                       columns.Bound(p => p.Id).ClientTemplate("<a class='blue_icon hover_disable_blue' href='" + Url.Action("Edit", "Exam", new { Id = "#=Id#" }) + "' data-mode='edit' ><i class='att att-edit (alias)'></i></a>").Title("").Width(15).Sortable(false);
                       columns.Bound(p => p.Id).ClientTemplate("<button class='no_bg red_icon' data-mode='deactivate' rowId='#=Id#'><i class='att att-times-circle'></i></button>").Title("").Width(25).Sortable(false);
                       columns.Bound(p => p.Id).Hidden(true);
                       columns.Bound(p => p.ExamType.Name).Sortable(true).Title(@L("MasterExamGridHeaderExamType").ToString()).Width(130);
                       columns.Bound(p => p.Name).Sortable(true).Title(@L("MasterExamGridHeaderExamName").ToString()).Width(130);
                       columns.Bound(p => p.DifficultLevelId).Sortable(true).Title(@L("MasterExamGridHeaderDifficultLevel").ToString()).Width(130);

                   })
                  .Events(x =>
                          {
                              x.DataBound("Exam.Handlers.ExamManager.onDataBound");
                          })
          .Pageable(pager => pager
              .Input(Model.GridView.PagerView.Input)
              .Numeric(Model.GridView.PagerView.Numeric)
              .Info(Model.GridView.PagerView.Info)
              .PreviousNext(Model.GridView.PagerView.PreviousNext)
              .Refresh(Model.GridView.PagerView.Refresh)
              .PageSizes(Model.GridView.PagerView.PageSizes)
          )
          .ToolBar(toolBar =>
                   {
                      toolBar.Template(@<text>
                        <a href="@Url.Action("Create", "Exam")" class="default_btn green_btn k-button k-button-icontext att att-plus"><span class="btn_text">@L("MasterExamButtonAdd").ToString()</span></a>
                       </text>);
                   })
                                  .Sortable(x => x.Enabled(true))
                                  .AutoBind(false)
                                  .Scrollable(x => x.Height("auto"))
                                  .Selectable(selectable => selectable.Mode(GridSelectionMode.Single))
                                  .DataSource(dataSource => dataSource
                                      .Ajax()
                                      .ServerOperation(false)
                                      .Model(model =>
                                             {
                                                 model.Id(p => p.Id);
                                             })
                                      .PageSize(10)
                                              .Read(read => read.Action("OnExamManagerGridRead", "Exam").Data("Exam.Handlers.ExamManager.getGridParameters"))

                                  )
        )
    </div>
</div>

trunk/aPortal/ATT-EXAM-KT-01-02_Practice/Exam/attune.Exam.Web/Areas/Master/Views/Exam/_QuestionSelection.cshtml
@model attune.Exam.Web.Areas.Master.Models.Exam.QuestionSelectionView



    <div id="divQsBank" class="ab_grid">
        @(Html.Kendo().Grid(Model.QuestionSelectionGridView.DataSource)
              .Name("questionSelectionGrid")
              .Columns(columns =>
                       {
                           columns.Template(@<text></text>).ClientTemplate("<input data-index='#= Index #' type='checkbox' class='chkList' # if (IsSelected == true){#" + "checked=checked" + "# } #/>").Width(22)
                               .HeaderTemplate("<input type='checkbox' id='chkAll'></input>");
                           columns.Bound(x => x.Id).Width(80);
                           columns.Bound(x => x.Question);
                           
                       })
                               .Pageable(pager => pager
                                          .Input(Model.QuestionSelectionGridView.PagerView.Input)
                                          .Numeric(Model.QuestionSelectionGridView.PagerView.Numeric)
                                          .Info(Model.QuestionSelectionGridView.PagerView.Info)
                                          .PreviousNext(Model.QuestionSelectionGridView.PagerView.PreviousNext)
                                  .PageSizes(Model.QuestionSelectionGridView.PagerView.PageSizes)
                                      )
                                      .Sortable(x => x.Enabled(false))
                                      .Scrollable(x => x.Height("auto"))
                                                      .Events(x => x.DataBound("Exam.Handlers.ExamManager.Questions.onDataBound"))
                                      .DataSource(dataSource => dataSource
                                          .Ajax().ServerOperation(false)
                                          .Model(model =>
                                                 {
                                                     model.Id(p => p.Id);
                                                 })
                                                          .PageSize(10)
                                                          .Read(read => read.Action("OnExamCategoryQuestionRead", "Exam").Data("Exam.Handlers.ExamManager.Questions.getQuestionSelectionGridParameters").Type(HttpVerbs.Get))
                                      ))

        <div class="button_row">
            <button id="btnAssign" class="default_btn green_btn att att-mail-forward (alias)"><span class="btn_text">@L("MasterExamButtonAssign")</span></button>
        </div>
    </div>
